/**
 * `packages/contracts` — the single source of truth for every interface.
 *
 * Depends on nothing but Zod. Everything depends on this.
 *
 * The `/connector/v1` types are published AS FROZEN. Session B keeps its own
 * dated snapshot and does not import this package (ADR-0015); four recommended
 * wire changes are recorded as HUMAN(CONNECTOR-nn) markers rather than applied.
 */

export {
  paiseWire,
  basisPointsWire,
  ratioWire,
  type Paise,
  type BasisPoints,
  type Ratio,
  type PaiseWire,
  type BasisPointsWire,
  type RatioWire,
} from './money.js';

export {
  principalKind,
  tenantContextWire,
  type TenantId,
  type PrincipalKind,
  type Principal,
  type TenantContext,
} from './tenant.js';

export {
  errorCode,
  apiError,
  HTTP_STATUS,
  type ErrorCode,
  type ApiError,
} from './errors.js';

export {
  cursor,
  pageRequest,
  pageOf,
  type PageRequest,
  type Page,
} from './pagination.js';

export {
  voucher,
  voucherKind,
  vouchersResponse,
  voucherResultStatus,
  voucherResultError,
  voucherResultRequest,
  voucherResultResponse,
  healthResponse,
  VOUCHER_KINDS,
  CONNECTOR_HEADERS,
  CONNECTOR_BASE_PATH,
  CONNECTOR_UPGRADE_REQUIRED_STATUS,
  type Voucher,
  type KnownVoucherKind,
  type VouchersResponse,
  type VoucherResultRequest,
  type HealthResponse,
} from './connector.js';

export {
  purchaseOrderLineInput,
  createPurchaseOrderInput,
  purchaseOrderNumberPreview,
  updatePurchaseOrderInput,
  renamePurchaseOrderInput,
  createPurchaseOrderFromBoqInput,
  vendor,
  createVendorInput,
  updateVendorInput,
  vendorListResponse,
  recordRetentionInput,
  retentionHolding,
  createStockItemInput,
  stockMovementInput,
  awaitingReceipt,
  stockLocation,
  stockLocationListResponse,
  createStockLocationInput,
  type StockLocation,
  awaitingReceiptListResponse,
  type AwaitingReceipt,
  stockTransferInput,
  stockBalance,
  stockItem,
  stockItemListResponse,
  stockListResponse,
  submitPurchaseOrderInput,
  purchaseOrderStateResponse,
  costingPolicyResponse,
  purchaseOrderWriteResponse,
  purchaseOrderTotalsResponse,
  purchaseOrderListItem,
  purchaseOrderListResponse,
  purchaseOrderFromBoqResponse,
  retentionListResponse,
  createdId,
  stockTransferResponse,
  vendorPortalOrder,
  vendorPortalOrderListResponse,
  vendorPortalLineListResponse,
  acceptOrderInput,
  orderAcceptanceResponse,
  vendorBill,
  vendorBillListResponse,
  submitBillInput,
  vendorTdsProfileInput,
  VENDOR_CONSTITUTIONS,
  recordTransporterDeclarationInput,
  transporterDeclaration,
  transporterDeclarationListResponse,
  type VendorConstitution,
  type RecordTransporterDeclarationInput,
  type TransporterDeclaration,
  type TransporterDeclarationListResponse,
  submittedBillResponse,
  whoamiResponse,
  type PurchaseOrderLineInput,
  type CreatePurchaseOrderInput,
  type PurchaseOrderNumberPreview,
  type UpdatePurchaseOrderInput,
  type RenamePurchaseOrderInput,
  type CreatePurchaseOrderFromBoqInput,
  type Vendor,
  type CreateVendorInput,
  type UpdateVendorInput,
  type VendorListResponse,
  type RecordRetentionInput,
  type RetentionHolding,
  type CreateStockItemInput,
  type StockMovementInput,
  type StockTransferInput,
  type StockBalance,
  type StockItem,
  type StockItemListResponse,
  type StockListResponse,
  type SubmitPurchaseOrderInput,
  type PurchaseOrderStateResponse,
  type CostingPolicyResponse,
  type PurchaseOrderWriteResponse,
  type PurchaseOrderTotalsResponse,
  type PurchaseOrderListResponse,
  type WhoamiResponse,
  type PurchaseOrderFromBoqResponse,
  type RetentionListResponse,
  type CreatedId,
  type StockTransferResponse,
  type VendorPortalOrder,
  type VendorPortalOrderListResponse,
  type VendorPortalLineListResponse,
  portalWhoamiResponse,
  type PortalWhoamiResponse,
  type AcceptOrderInput,
  type VendorBill,
  type VendorBillListResponse,
  type SubmitBillInput,
} from './api/purchase-orders.js';

export {
  defineRoute,
  noContent,
  API_ROUTES,
  type HttpMethod,
  type RouteDescriptor,
  type PathParams,
  type ApiRoutes,
} from './api/routes.js';

export {
  absentStat,
  blockedApproval,
  approvalOwner,
  blockedApprovalsStat,
  marginAtRiskStat,
  type MarginAtRiskStat,
  cashAgainstPayablesStat,
  type CashAgainstPayablesStat,
  heroCandidate,
  todayHeroResponse,
  setupStep,
  todaySetupResponse,
  tallyPresence,
  type TallyPresence,
  type AbsentStat,
  type TodaySetupResponse,
  type BlockedApproval,
  type BlockedApprovalsStat,
  type HeroCandidate,
  type TodayHeroResponse,
  spendByTradeItem,
  spendByTradeResponse,
  type SpendByTradeItem,
  type SpendByTradeResponse,
} from './api/today.js';

export {
  createClient,
  ApiContractError,
  ApiTransportError,
  type ApiClient,
  type ApiResult,
  type AnyRoute,
  type RouteResponse,
  type RouteOptions,
  type ClientOptions,
  type CallOptions,
} from './api/client.js';

export {
  projectState,
  project,
  createProjectInput,
  setProjectStateInput,
  projectListResponse,
  boqItem,
  boqResponse,
  boqLineInput,
  createTakeoffSheetInput,
  takeoffItemInput,
  saveTakeoffItemsInput,
  takeoffSummary,
  createEstimationItemInput,
  rateAnalysis,
  estimationItem,
  issueDrawingInput,
  gfcDrawing,
  createChangeOrderInput,
  decideChangeOrderInput,
  submitChangeOrderInput,
  changeOrder,
  contractValueResponse,
  createLeadInput,
  updateLeadInput,
  convertLeadInput,
  lead,
  LEAD_STAGES,
  pipelineResponse,
  addBoqLinesInput,
  updateBoqLineInput,
  projectHealthBand,
  projectRollupItem,
  projectRollupResponse,
  boqWriteResponse,
  drawingListResponse,
  estimationListResponse,
  takeoffSheet,
  takeoffSheetListResponse,
  clientPortalProject,
  clientPortalProjectListResponse,
  clientPortalVariation,
  clientPortalVariationListResponse,
  type ProjectState,
  type Project,
  type CreateProjectInput,
  type SetProjectStateInput,
  type ProjectListResponse,
  type BoqResponse,
  type BoqLineInput,
  type CreateTakeoffSheetInput,
  type TakeoffItemInput,
  type SaveTakeoffItemsInput,
  type TakeoffSummary,
  type CreateEstimationItemInput,
  type RateAnalysisResponse,
  type EstimationItem,
  type IssueDrawingInput,
  type GfcDrawing,
  type CreateChangeOrderInput,
  type DecideChangeOrderInput,
  type SubmitChangeOrderInput,
  type ChangeOrder,
  unsignedVariation,
  unsignedVariationsResponse,
  pipelineSlice,
  pipelineSummaryResponse,
  type UnsignedVariationsResponse,
  type PipelineSummaryResponse,
  type ContractValueResponse,
  type CreateLeadInput,
  type UpdateLeadInput,
  type ConvertLeadInput,
  type Lead,
  type PipelineResponse,
  type AddBoqLinesInput,
  type UpdateBoqLineInput,
  type ProjectHealthBand,
  type ProjectRollupResponse,
  type BoqWriteResponse,
  type DrawingListResponse,
  type EstimationListResponse,
  type TakeoffSheet,
  type TakeoffSheetListResponse,
  type ClientPortalProject,
  type ClientPortalProjectListResponse,
  type ClientPortalVariation,
  type ClientPortalVariationListResponse,
  leadContact,
  projectMember,
  projectTeamResponse,
  addProjectMemberInput,
  leadContactListResponse,
  addLeadContactInput,
  leadActivity,
  leadActivityListResponse,
  recordLeadActivityInput,
  markLeadLostInput,
  possibleDuplicateResponse,
  type LeadContact,
  type ProjectMember,
  type ProjectTeamResponse,
  type AddProjectMemberInput,
  type LeadContactListResponse,
  type AddLeadContactInput,
  type LeadActivity,
  type LeadActivityListResponse,
  type RecordLeadActivityInput,
  type MarkLeadLostInput,
  type PossibleDuplicateResponse,
} from './api/projects.js';

export {
  approvalStage,
  approvalChain,
  approvalChainsResponse,
  recordComment,
  recordCommentsResponse,
  addCommentInput,
  notification,
  notificationsResponse,
  markAllNotificationsReadResponse,
  type Notification,
  type NotificationsResponse,
  approvalHistoryEntry,
  approvalHistoryResponse,
  auditEntry,
  auditResponse,
  registerDocumentInput,
  documentRecord,
  createTaskInput,
  updateTaskInput,
  task,
  taskListResponse,
  documentListResponse,
  decideApprovalInput,
  declineApprovalInput,
  approvalDecisionResponse,
  type ApprovalChainsResponse,
  type ApprovalHistoryResponse,
  type AuditResponse,
  type RegisterDocumentInput,
  type DocumentRecord,
  type CreateTaskInput,
  type UpdateTaskInput,
  type Task,
  type TaskListResponse,
  type DocumentListResponse,
  type DecideApprovalInput,
  type ApprovalDecisionResponse,
} from './api/workflow.js';

export {
  manpowerEntry,
  dailyReport,
  dailyReportsResponse,
  createDailyReportInput,
  siteIssue,
  siteIssueSeverity,
  siteIssueListResponse,
  raiseSiteIssueInput,
  resolveSiteIssueInput,
  siteTodayResponse,
  SITE_ISSUE_SEVERITIES,
  type SiteIssue,
  type SiteIssueListResponse,
  type SiteTodayResponse,
  weeklyAggregateResponse,
  createRecceInput,
  requestImprestInput,
  sanctionImprestInput,
  reconcileImprestInput,
  imprest,
  recordMeasurementInput,
  imprestListResponse,
  measurement,
  measurementListResponse,
  recce,
  recceListResponse,
  type DailyReportsResponse,
  type CreateDailyReportInput,
  type WeeklyAggregateResponse,
  type CreateRecceInput,
  type RequestImprestInput,
  type SanctionImprestInput,
  type ReconcileImprestInput,
  type Imprest,
  type RecordMeasurementInput,
  type ImprestListResponse,
  type Measurement,
  type MeasurementListResponse,
  type Recce,
  type RecceListResponse,
} from './api/siteops.js';

export {
  principal,
  principalsResponse,
  invite,
  invitesResponse,
  invitableKind,
  type InvitableKind,
  createInviteInput,
  mintedInviteResponse,
  tenantSettings,
  platformTenant,
  setTenantPlanInput,
  platformTenantListResponse,
  platformWhoamiResponse,
  provisionTenantInput,
  provisionedTenantResponse,
  provisioningEvent,
  provisioningEventListResponse,
  type PrincipalsResponse,
  type InvitesResponse,
  type CreateInviteInput,
  type MintedInviteResponse,
  type TenantSettings,
  type PlatformTenant,
  type PlatformTenantListResponse,
  type PlatformWhoamiResponse,
  type ProvisionTenantInput,
  type ProvisionedTenantResponse,
  type ProvisioningEventListResponse,
  entitlementsResponse,
  roleRow,
  roleListResponse,
  setRoleGrantsInput,
  addRoleInput,
  okResponse,
  configureChainInput,
  taxRateRow,
  taxRateListResponse,
  recordTaxRateInput,
  tdsThresholdRow,
  tdsThresholdListResponse,
  loadStatutoryCatalogueResponse,
  configuredChainResponse,
  type EntitlementsResponse,
  type RoleRow,
  type RoleListResponse,
  type SetRoleGrantsInput,
  type AddRoleInput,
  type ConfigureChainInput,
  type TaxRateRow,
  type TaxRateListResponse,
  type RecordTaxRateInput,
  type ConfiguredChainResponse,
} from './api/identity.js';

/**
 * The role model's vocabulary and its provisional default (PO-13). Not a
 * policy: every grant is a row, and this only names the strings a row may hold.
 */
export {
  MODULES,
  ACTIONS,
  MODULE_KEYS,
  ACTION_KEYS,
  DEFAULT_ROLES,
  DEFAULT_CHAINS,
  type ModuleKey,
  type ActionKey,
  type RoleDefault,
  type StageDefault,
  type ChainDefault,
} from './authz.js';

/**
 * Optional modules — whether a feature is switched on for a tenant at all,
 * which is a different question from whether a role may reach it.
 */
export {
  moduleState,
  moduleListResponse,
  setModuleInput,
  setModuleResponse,
  type ModuleState,
  type ModuleListResponse,
  type SetModuleInput,
  type SetModuleResponse,
} from './api/tenancy.js';

/** Terminology — the words this firm uses, one per pair, read by every label. */
export {
  TERM_OPTIONS,
  TERM_KEYS,
  terminology,
  terminologyResponse,
  saveTerminologyInput,
  type TermKey,
  type Terminology,
  type TerminologyResponse,
  type SaveTerminologyInput,
} from './api/tenancy.js';

/** Document numbering — the format, never the counter. */
export {
  FY_FORMAT_KEYS,
  numberSeriesFormat,
  numberSeriesRow,
  numberSeriesListResponse,
  saveNumberSeriesInput,
  type NumberSeriesFormat,
  type NumberSeriesRow,
  type NumberSeriesListResponse,
  type SaveNumberSeriesInput,
} from './api/purchase-orders.js';

/** Trade packages — the catalogue behind a trade and a BOQ section. */
export {
  tradePackage,
  tradePackageListResponse,
  tradePackageInput,
  updateTradePackageInput,
  tradePackageCreated,
  type TradePackage,
  type TradePackageListResponse,
  type TradePackageInput,
  type UpdateTradePackageInput,
} from './api/projects.js';

/** The organisation's own details, and the defaults it works to. */
export {
  companyProfile,
  saveCompanyProfileInput,
  operationalDefaults,
  saveOperationalDefaultsInput,
  taxSetup,
  saveTaxSetupInput,
  type CompanyProfile,
  type SaveCompanyProfileInput,
  type OperationalDefaults,
  type SaveOperationalDefaultsInput,
  type TaxSetup,
  type SaveTaxSetupInput,
} from './api/tenancy.js';

/**
 * People, the client logins that see one project each, and the vendor logins
 * that see one supplier's orders each. The last two are the same mechanism —
 * `principal_links` — with two different subject kinds.
 */
export {
  person,
  peopleResponse,
  clientAccount,
  clientAccountsResponse,
  grantClientProjectInput,
  vendorAccount,
  vendorAccountsResponse,
  grantVendorInput,
  type Person,
  type PeopleResponse,
  type ClientAccount,
  type ClientAccountsResponse,
  type GrantClientProjectInput,
  type VendorAccount,
  type VendorAccountsResponse,
  type GrantVendorInput,
} from './api/identity.js';

/** Merging duplicate opportunities, and the record of every merge. */
export {
  mergeLeadsInput,
  mergeLeadsResponse,
  leadMerge,
  leadMergeListResponse,
  type MergeLeadsInput,
  type MergeLeadsResponse,
  type LeadMerge,
  type LeadMergeListResponse,
} from './api/projects.js';

/** Handing a won opportunity to the people who will build it. */
export {
  handoverLeadInput,
  handoverLeadResponse,
  type HandoverLeadInput,
  type HandoverLeadResponse,
} from './api/projects.js';

/**
 * The eleven design-build workflows. Each one is off by default and every
 * route under `/api/v1/design-build` answers 404 when its module is off.
 */
export {
  BRIEF_STATUS_KEYS,
  STATEMENT_KIND_KEYS,
  briefStatement,
  briefRoom,
  clientBrief,
  briefListResponse,
  saveBriefInput,
  setBriefStatusInput,
  addStatementInput,
  saveRoomInput,
  type BriefStatement,
  type BriefRoom,
  type ClientBrief,
  type BriefListResponse,
  type SaveBriefInput,
  type SetBriefStatusInput,
  type AddStatementInput,
  type SaveRoomInput,
} from './api/design-build.js';

/** Design-build workflows 2 and 3. */
export {
  DELIVERABLE_STATUS_KEYS,
  REVIEW_DECISION_KEYS,
  SELECTION_STATUS_KEYS,
  designReview,
  designDeliverable,
  deliverableListResponse,
  addDeliverableInput,
  reviewDeliverableInput,
  reviewResult,
  substitution,
  roomSelection,
  selectionListResponse,
  addSelectionInput,
  decideSelectionInput,
  proposeSubstitutionInput,
  decideSubstitutionInput,
  substitutionResult,
  type DesignReview,
  type DesignDeliverable,
  type DeliverableListResponse,
  type AddDeliverableInput,
  type ReviewDeliverableInput,
  type ReviewResult,
  type Substitution,
  type RoomSelection,
  type SelectionListResponse,
  type AddSelectionInput,
  type DecideSelectionInput,
  type ProposeSubstitutionInput,
  type DecideSubstitutionInput,
  type SubstitutionResult,
} from './api/design-build.js';

/** Design-build workflows 4 and 5. */
export {
  agreementStage,
  commercialAgreement,
  agreementResponse,
  saveAgreementInput,
  setStagesInput,
  setAgreementStatusInput,
  leadTimeConflict,
  procurementPlanResponse,
  type AgreementStage,
  type CommercialAgreement,
  type AgreementResponse,
  type SaveAgreementInput,
  type SetStagesInput,
  type SetAgreementStatusInput,
  type LeadTimeConflict,
  type ProcurementPlanResponse,
} from './api/design-build.js';

/** Design-build workflows 6 and 7. */
export {
  MILESTONE_STATUS_KEYS,
  joineryStage,
  joineryPackage,
  joineryListResponse,
  addPackageInput,
  advanceStageInput,
  advanceResult,
  deliveryMilestone,
  milestoneListResponse,
  addMilestoneInput,
  recordProgressInput,
  type JoineryStage,
  type JoineryPackage,
  type JoineryListResponse,
  type AddPackageInput,
  type AdvanceStageInput,
  type AdvanceResult,
  type DeliveryMilestone,
  type MilestoneListResponse,
  type AddMilestoneInput,
  type RecordProgressInput,
  milestoneThisWeek,
  milestonesThisWeekResponse,
  type MilestoneThisWeek,
  type MilestonesThisWeekResponse,
} from './api/design-build.js';

/** Design-build workflows 8 and 9. */
export {
  ITEM_KIND_KEYS,
  SEVERITY_KEYS,
  ITEM_STATUS_KEYS,
  WARRANTY_STATUS_KEYS,
  handoverItem,
  handoverRecord,
  handoverStateResponse,
  raiseItemInput,
  rectifyItemInput,
  issueHandoverInput,
  warrantyCase,
  warrantyListResponse,
  raiseCaseInput,
  decideCaseInput,
  type HandoverItem,
  type HandoverRecord,
  type HandoverStateResponse,
  type RaiseItemInput,
  type RectifyItemInput,
  type IssueHandoverInput,
  type WarrantyCase,
  type WarrantyListResponse,
  type RaiseCaseInput,
  type DecideCaseInput,
} from './api/design-build.js';

/** Design-build workflows 10 and 11. */
export {
  DECISION_CHANNEL_KEYS,
  SUBJECT_KIND_KEYS,
  timesheetEntry,
  timesheetSummary,
  timesheetResponse,
  bookTimeInput,
  clientActionItem,
  clientDecisionRecord,
  clientActionsResponse,
  externalDecisionInput,
  type TimesheetEntry,
  type TimesheetSummary,
  type TimesheetResponse,
  type BookTimeInput,
  type ClientActionItem,
  type ClientDecisionRecord,
  type ClientActionsResponse,
  type ExternalDecisionInput,
} from './api/design-build.js';

export {
  rateContractDetail,
  rateContractInput,
  rateContractItemInput,
  rateContractSummary,
  rateContractsResponse,
  rateDeviation,
  rateDeviationsResponse,
  purchaseOrderLine,
  purchaseOrderLinesResponse,
  type PurchaseOrderLine,
  type PurchaseOrderLinesResponse,
  type RateContractInputWire,
} from './api/purchase-orders.js';
export { weeklySeriesResponse, type WeeklySeriesResponse } from './api/today.js';
export { rateCoverageResponse, rateLibraryRow, rateLibraryResponse, type RateCoverageResponse, type RateLibraryRow, type RateLibraryResponse } from './api/projects.js';

export {
  staffBill,
  payablesBucket,
  payablesSummary,
  billView,
  billListResponse,
  acknowledgeBillInput,
  tdsReason,
  vendorPayment,
  paymentSummary,
  paymentListResponse,
  payBillInput,
  vendorPortalPayment,
  vendorPortalPaymentListResponse,
  retentionPosition,
  retentionPositionListResponse,
  challanLine,
  tdsChallanResponse,
  clientInvoice,
  receivablesSummary,
  ageingBucket,
  ageingBuckets,
  receivablesAgeingResponse,
  payablesAgeingResponse,
  moneyPeriod,
  moneyByMonthResponse,
  type AgeingBucket,
  type AgeingBuckets,
  type ReceivablesAgeingResponse,
  type PayablesAgeingResponse,
  type MoneyPeriod,
  type MoneyByMonthResponse,
  clientInvoiceListResponse,
  raiseClientInvoiceInput,
  recordClientReceiptInput,
  cancelClientInvoiceInput,
  clientPortalInvoice,
  clientPortalBillingResponse,
  type ClientInvoice,
  type ReceivablesSummary,
  type ClientInvoiceListResponse,
  type RaiseClientInvoiceInput,
  type RecordClientReceiptInput,
  type CancelClientInvoiceInput,
  type ClientPortalInvoice,
  type ClientPortalBillingResponse,
  form26QRow,
  form26QResponse,
  type ChallanLine,
  type TdsChallanResponse,
  type Form26QRow,
  type Form26QResponse,
  releaseRetentionInput,
  type RetentionPosition,
  type RetentionPositionListResponse,
  type ReleaseRetentionInput,
  type VendorPortalPayment,
  type VendorPortalPaymentListResponse,
  type TdsReason,
  type VendorPayment,
  type PaymentSummary,
  type PaymentListResponse,
  type PayBillInput,
  type StaffBill,
  type PayablesBucket,
  type PayablesSummary,
  type BillView,
  type BillListResponse,
  type AcknowledgeBillInput,
} from './api/money.js';

export {
  shellCountsResponse,
  myProjectsResponse,
  recordKind,
  historyItem,
  recentHistoryResponse,
  recordOpenedInput,
  preferences,
  preferencesResponse,
  updatePreferencesInput,
  quickCreateItem,
  quickCreateResponse,
  searchHit,
  searchResponse,
  savedView,
  savedViewsResponse,
  createSavedViewInput,
  type ShellCountsResponse,
  type MyProjectsResponse,
  type RecordKind,
  type HistoryItem,
  type RecentHistoryResponse,
  type RecordOpenedInput,
  type Preferences,
  type UpdatePreferencesInput,
  type QuickCreateResponse,
  type SearchResponse,
  type SavedView,
  type CreateSavedViewInput,
} from './api/shell.js';
