/* Generated by scripts/import-drawings.mjs from docs/design/build/{icons,duotone,illustrations}.mjs — do not edit;
   run the script. 57 icons on the 16px grid, 19 duotones on 24, 23 illustrations on 160. */
import type { ReactNode } from 'react';

export const ICON_NAMES = [
  'home',
  'sales',
  'projects',
  'cart',
  'site',
  'check-sq',
  'rupee',
  'cog',
  'menu',
  'search',
  'bell',
  'plus',
  'download',
  'link',
  'x',
  'check',
  'alert',
  'info',
  'refresh',
  'copy',
  'pen',
  'clock',
  'inbox',
  'bill',
  'doc',
  'users',
  'monitor',
  'sun',
  'moon',
  'caret',
  'paperclip',
  'star',
  'mark',
  'hammer',
  'flag',
  'chart',
  'ruler',
  'shield',
  'grid',
  'timeline',
  'upload',
  'chevron',
  'sort',
  'left',
  'right',
  'up',
  'down',
  'layers',
  'more',
  'columns',
  'lock',
  'expand',
  'calendar',
  'check-circle',
  'help',
  'collapse',
  'settings',
] as const;
export type IconName = (typeof ICON_NAMES)[number];

export const DUOTONE_NAMES = [
  'margin',
  'bill',
  'ceiling',
  'contract',
  'site',
  'tray',
  'voucher',
  'invoice-in',
  'invoice-out',
  'orders',
  'due',
  'stock',
  'count',
  'people',
  'held',
  'firm',
  'flow',
  'record',
  'yours',
] as const;
export type DuotoneName = (typeof DUOTONE_NAMES)[number];

/** The subjects drawn — one drawing per subject. */
export const ILLUSTRATION_SUBJECTS = [
  'today',
  'tasks',
  'notifications',
  'sales',
  'projects',
  'boq',
  'rates',
  'orders',
  'stock',
  'vendors',
  'approvals',
  'daily',
  'measure',
  'recce',
  'documents',
  'money',
  'chai',
  'search',
  'not-found',
  'unreachable',
  'error',
  'signed-out',
  'operator',
] as const;
export type IllustrationSubject = (typeof ILLUSTRATION_SUBJECTS)[number];

/** Each empty state's name → the subject it draws (ILLO_FOR in illustrations.mjs). */
export const ILLUSTRATION_FOR = {
  'today': 'today',
  'tasks': 'tasks',
  'notifications': 'notifications',
  'leads': 'sales',
  'projects': 'projects',
  'boq': 'boq',
  'rates': 'rates',
  'orders': 'orders',
  'stock': 'stock',
  'vendors': 'vendors',
  'approvals': 'approvals',
  'daily': 'daily',
  'measure': 'measure',
  'recce': 'recce',
  'documents': 'documents',
  'money': 'money',
  'search': 'search',
  'not-found': 'not-found',
  'unreachable': 'unreachable',
  'error': 'error',
  'signed-out': 'signed-out',
  'operator': 'operator',
  'client': 'chai',
} as const satisfies Record<string, IllustrationSubject>;
export type IllustrationName = keyof typeof ILLUSTRATION_FOR;
export const ILLUSTRATION_NAMES = Object.keys(ILLUSTRATION_FOR) as readonly IllustrationName[];

/** What each subject is, for a reader (ILLO_CAPTION). */
export const ILLUSTRATION_CAPTION = {
  'today': 'sunrise over a site board',
  'tasks': 'a checklist',
  'notifications': 'a bell',
  'sales': 'a lead card',
  'projects': 'a floor plan',
  'boq': 'a BOQ sheet',
  'rates': 'a calculator',
  'orders': 'an order form',
  'stock': 'a delivery crate',
  'vendors': 'a shop front',
  'approvals': 'an empty in-tray',
  'daily': 'a site cone',
  'measure': 'a tape measure',
  'recce': 'a camera',
  'documents': 'a drawing roll',
  'money': 'a paid voucher',
  'search': 'a magnifier',
  'not-found': 'a signpost',
  'unreachable': 'an unplugged cable',
  'error': 'a warning triangle',
  'signed-out': 'a key',
  'operator': 'a row of buildings',
  'chai': 'a cup of chai',
} as const satisfies Record<IllustrationSubject, string>;

/** A monoline icon's name → the duotone that does its job on a disc (DUO_FOR_ICON). */
export const DUOTONE_FOR_ICON = {
  'cart': 'orders',
  'site': 'site',
  'users': 'people',
  'clock': 'due',
  'rupee': 'voucher',
  'layers': 'stock',
  'doc': 'count',
  'inbox': 'tray',
  'check-sq': 'tray',
  'lock': 'held',
  'bill': 'bill',
  'alert': 'ceiling',
} as const satisfies Record<string, DuotoneName>;

/** Every symbol, inside one hidden svg; `Sprite` renders it once per document. */
export function DrawingSymbols(): ReactNode {
  return (
    <>
      <symbol id="i-home" viewBox="0 0 16 16">
        <path d="M2.75 7.25 8 2.75l5.25 4.5v6H2.75z" /><path d="M6.5 13.25v-3.5h3v3.5" />
      </symbol>
      <symbol id="i-sales" viewBox="0 0 16 16">
        <path d="M2.75 11.25 6.25 7.75l2.5 2.5 4.5-4.5" /><path d="M10.25 5.75h3v3" />
      </symbol>
      <symbol id="i-projects" viewBox="0 0 16 16">
        <path d="M2.75 4.25a1 1 0 0 1 1-1h2.5l1.5 1.5h4.5a1 1 0 0 1 1 1v6.5a1 1 0 0 1-1 1h-8.5a1 1 0 0 1-1-1z" />
      </symbol>
      <symbol id="i-cart" viewBox="0 0 16 16">
        <path d="M1.75 2.75h1.5l1.5 7h7l1.25-5H4" /><path d="M6 12.75h.01M11 12.75h.01" strokeWidth="2" />
      </symbol>
      <symbol id="i-site" viewBox="0 0 16 16">
        <path d="M2.25 13.25h11.5" /><path d="M4.25 13.25v-7l3.75-3 3.75 3v7" /><path d="M6.5 13.25v-3h3v3" />
      </symbol>
      <symbol id="i-check-sq" viewBox="0 0 16 16">
        <rect x="2.75" y="2.75" width="10.5" height="10.5" rx="1.5" /><path d="M5.5 8.25 7.25 10l3.25-3.5" />
      </symbol>
      <symbol id="i-rupee" viewBox="0 0 16 16">
        <path d="M4.75 2.75h6.5M4.75 5.75h6.5" /><path d="M4.75 2.75c3.25 0 4.5 1.25 4.5 2.75s-1.25 2.75-4.5 2.75l4.5 5" />
      </symbol>
      <symbol id="i-cog" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="2" /><path d="M8 1.75v1.75M8 12.5v1.75M1.75 8H3.5M12.5 8h1.75M3.58 3.58 4.82 4.82M11.18 11.18l1.24 1.24M3.58 12.42l1.24-1.24M11.18 4.82l1.24-1.24" /><circle cx="8" cy="8" r="4.5" />
      </symbol>
      <symbol id="i-menu" viewBox="0 0 16 16">
        <path d="M2.75 4.25h10.5M2.75 8h10.5M2.75 11.75h10.5" />
      </symbol>
      <symbol id="i-search" viewBox="0 0 16 16">
        <circle cx="7" cy="7" r="4.25" /><path d="m10.25 10.25 3 3" />
      </symbol>
      <symbol id="i-bell" viewBox="0 0 16 16">
        <path d="M4.25 11V7.25a3.75 3.75 0 0 1 7.5 0V11l1 1.25H3.25z" /><path d="M6.75 14h2.5" />
      </symbol>
      <symbol id="i-plus" viewBox="0 0 16 16">
        <path d="M8 3.25v9.5M3.25 8h9.5" />
      </symbol>
      <symbol id="i-download" viewBox="0 0 16 16">
        <path d="M8 2.75v7" /><path d="M5 7l3 3 3-3" /><path d="M3.25 13.25h9.5" />
      </symbol>
      <symbol id="i-link" viewBox="0 0 16 16">
        <path d="M6.75 9.25a2.5 2.5 0 0 0 3.5 0l2-2a2.5 2.5 0 0 0-3.5-3.5l-.75.75" /><path d="M9.25 6.75a2.5 2.5 0 0 0-3.5 0l-2 2a2.5 2.5 0 0 0 3.5 3.5l.75-.75" />
      </symbol>
      <symbol id="i-x" viewBox="0 0 16 16">
        <path d="m4.25 4.25 7.5 7.5M11.75 4.25l-7.5 7.5" />
      </symbol>
      <symbol id="i-check" viewBox="0 0 16 16">
        <path d="M3.25 8.5l3 3 6.5-7" />
      </symbol>
      <symbol id="i-alert" viewBox="0 0 16 16">
        <path d="M8 2.5l6 10.75H2z" /><path d="M8 6.5v2.75M8 11.5h.01" />
      </symbol>
      <symbol id="i-info" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="5.75" /><path d="M8 7.25v4M8 4.75h.01" />
      </symbol>
      <symbol id="i-refresh" viewBox="0 0 16 16">
        <path d="M12.75 8a4.75 4.75 0 0 1-8.4 3.05M3.25 8a4.75 4.75 0 0 1 8.4-3.05" /><path d="M11.75 2.25V5H9M4.25 13.75V11H7" />
      </symbol>
      <symbol id="i-copy" viewBox="0 0 16 16">
        <rect x="5.75" y="5.75" width="7.5" height="7.5" rx="1" /><path d="M3.25 10.25v-6.5a1 1 0 0 1 1-1h6.5" />
      </symbol>
      <symbol id="i-pen" viewBox="0 0 16 16">
        <path d="M3 13l.75-3L10.5 3.25l2.25 2.25L6 12.25z" /><path d="M9 4.75l2.25 2.25" />
      </symbol>
      <symbol id="i-clock" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="5.75" /><path d="M8 4.75V8l2.25 1.5" />
      </symbol>
      <symbol id="i-inbox" viewBox="0 0 16 16">
        <path d="M2.75 8.75h3l1 1.5h2.5l1-1.5h3" /><path d="M2.75 8.75l1.5-5.5h7.5l1.5 5.5v4.5H2.75z" />
      </symbol>
      <symbol id="i-bill" viewBox="0 0 16 16">
        <path d="M3.75 2.25h8.5v11.5l-2-1.25-2.25 1.25-2.25-1.25-2 1.25z" /><path d="M6 5.75h4M6 8.25h4" />
      </symbol>
      <symbol id="i-doc" viewBox="0 0 16 16">
        <path d="M4.25 1.75H9l2.75 2.75v9.75h-7.5z" /><path d="M9 1.75V4.5h2.75M6.25 8.25h3.5M6.25 10.75h3.5" />
      </symbol>
      <symbol id="i-users" viewBox="0 0 16 16">
        <circle cx="6" cy="5.25" r="2.25" /><path d="M2.25 13.25a3.75 3.75 0 0 1 7.5 0" /><path d="M10.25 3a2.25 2.25 0 0 1 0 4.5M11.25 9.75a3.5 3.5 0 0 1 2.5 3.5" />
      </symbol>
      <symbol id="i-monitor" viewBox="0 0 16 16">
        <rect x="1.75" y="2.75" width="12.5" height="8.5" rx="1" /><path d="M5.5 13.75h5M8 11.25v2.5" />
      </symbol>
      <symbol id="i-sun" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="2.75" /><path d="M8 1.75v1M8 13.25v1M1.75 8h1M13.25 8h1M3.58 3.58l.7.7M11.72 11.72l.7.7M3.58 12.42l.7-.7M11.72 4.28l.7-.7" />
      </symbol>
      <symbol id="i-moon" viewBox="0 0 16 16">
        <path d="M13 9.5A5.5 5.5 0 0 1 6.5 3a5.5 5.5 0 1 0 6.5 6.5z" />
      </symbol>
      <symbol id="i-caret" viewBox="0 0 16 16">
        <path d="M4 6.5h8L8 11z" fill="currentColor" stroke="none" />
      </symbol>
      <symbol id="i-paperclip" viewBox="0 0 16 16">
        <path d="M10.5 5.5 6.2 9.8a1.5 1.5 0 0 0 2.1 2.1l4.6-4.6a3 3 0 0 0-4.2-4.2L4.1 7.7a4.5 4.5 0 0 0 6.4 6.4l3.5-3.5" />
      </symbol>
      <symbol id="i-star" viewBox="0 0 16 16">
        <path d="m8 2.2 1.8 3.7 4 .6-2.9 2.8.7 4L8 11.4l-3.6 1.9.7-4L2.2 6.5l4-.6z" />
      </symbol>
      <symbol id="i-mark" viewBox="0 0 16 16">
        <path d="M2.5 8.5 8 3l5.5 5.5M4 7.5V13h8V7.5" /><path d="M6.5 13v-3h3v3" />
      </symbol>
      <symbol id="i-hammer" viewBox="0 0 16 16">
        <path d="m9.5 6.5 4 4-1.5 1.5-4-4M3 13l4.5-4.5M6 3.5l3 3M4.5 5 6 3.5l2 2L6.5 7z" />
      </symbol>
      <symbol id="i-flag" viewBox="0 0 16 16">
        <path d="M4 14V2.5M4 3h8l-2 3 2 3H4" />
      </symbol>
      <symbol id="i-chart" viewBox="0 0 16 16">
        <path d="M3 13h10M4.5 11V7M8 11V4M11.5 11V8.5" />
      </symbol>
      <symbol id="i-ruler" viewBox="0 0 16 16">
        <path d="m2.5 10.5 8-8 3 3-8 8zM5 8l1.5 1.5M7 6l1.5 1.5M9 4l1.5 1.5" />
      </symbol>
      <symbol id="i-shield" viewBox="0 0 16 16">
        <path d="M8 2.5 3.5 4v4c0 2.8 2 4.6 4.5 5.5 2.5-.9 4.5-2.7 4.5-5.5V4z" />
      </symbol>
      <symbol id="i-grid" viewBox="0 0 16 16">
        <path d="M3 3h4v4H3zM9 3h4v4H9zM3 9h4v4H3zM9 9h4v4H9z" />
      </symbol>
      <symbol id="i-timeline" viewBox="0 0 16 16">
        <path d="M2.5 8h11M5 8V5M8 8v3M11 8V5" /><circle cx="5" cy="4" r="1" /><circle cx="8" cy="12" r="1" /><circle cx="11" cy="4" r="1" />
      </symbol>
      <symbol id="i-upload" viewBox="0 0 16 16">
        <path d="M8 11V3M4.5 6.5 8 3l3.5 3.5M3 13h10" />
      </symbol>
      <symbol id="i-chevron" viewBox="0 0 16 16">
        <path d="M4.75 6.5 8 9.75l3.25-3.25" />
      </symbol>
      <symbol id="i-sort" viewBox="0 0 16 16">
        <path d="M8 3.25v9.5" /><path d="M5 9.75l3 3 3-3" />
      </symbol>
      <symbol id="i-left" viewBox="0 0 16 16">
        <path d="M10 3.75 5.75 8 10 12.25" />
      </symbol>
      <symbol id="i-right" viewBox="0 0 16 16">
        <path d="M6 3.75 10.25 8 6 12.25" />
      </symbol>
      <symbol id="i-up" viewBox="0 0 16 16">
        <path d="M8 12.75V3.5" /><path d="M4.75 6.5 8 3.25l3.25 3.25" />
      </symbol>
      <symbol id="i-down" viewBox="0 0 16 16">
        <path d="M8 3.25v9.25" /><path d="M4.75 9.5 8 12.75l3.25-3.25" />
      </symbol>
      <symbol id="i-layers" viewBox="0 0 16 16">
        <path d="M8 2.25l5.75 3L8 8.25l-5.75-3z" /><path d="M2.25 8.75 8 11.75l5.75-3" />
      </symbol>
      <symbol id="i-more" viewBox="0 0 16 16">
        <path d="M3.5 8h.01M8 8h.01M12.5 8h.01" strokeWidth="2.25" />
      </symbol>
      <symbol id="i-columns" viewBox="0 0 16 16">
        <rect x="2.25" y="3.25" width="11.5" height="9.5" rx="1" /><path d="M6.25 3.25v9.5M9.75 3.25v9.5" />
      </symbol>
      <symbol id="i-lock" viewBox="0 0 16 16">
        <rect x="3.25" y="7.25" width="9.5" height="6.5" rx="1" /><path d="M5.25 7.25v-2a2.75 2.75 0 0 1 5.5 0v2" />
      </symbol>
      <symbol id="i-expand" viewBox="0 0 16 16">
        <path d="M9.5 2.75h3.75V6.5M13.25 2.75 9 7M6.5 13.25H2.75V9.5M2.75 13.25 7 9" />
      </symbol>
      <symbol id="i-calendar" viewBox="0 0 16 16">
        <rect x="2.25" y="3.25" width="11.5" height="10" rx="1" /><path d="M2.25 6.25h11.5M5.25 1.75v3M10.75 1.75v3" />
      </symbol>
      <symbol id="i-check-circle" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="5.75" /><path d="M5.5 8.25 7.25 10l3.25-3.5" />
      </symbol>
      <symbol id="i-help" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="5.75" /><path d="M6.25 6.5a1.75 1.75 0 1 1 2.5 1.6c-.55.3-.75.6-.75 1.15M8 11.5h.01" />
      </symbol>
      <symbol id="i-collapse" viewBox="0 0 16 16">
        <path d="M13.25 3.25v9.5" /><path d="M9.5 4.75 6.25 8l3.25 3.25M6.25 8h-4" />
      </symbol>
      <symbol id="i-settings" viewBox="0 0 16 16">
        <circle cx="8" cy="8" r="2" /><path d="M8 1.75v1.75M8 12.5v1.75M1.75 8H3.5M12.5 8h1.75M3.58 3.58 4.82 4.82M11.18 11.18l1.24 1.24M3.58 12.42l1.24-1.24M11.18 4.82l1.24-1.24" /><circle cx="8" cy="8" r="4.5" />
      </symbol>
      <symbol id="d-margin" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 12h14v4H5z" /><path className="l" d="M5 3h10l4 4v14H5z" /><path className="l" d="M15 3v4h4M8 8h4M8 19h7" />
      </symbol>
      <symbol id="d-bill" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 2.5h14v19l-2.33-1.8-2.34 1.8-2.33-1.8-2.33 1.8-2.34-1.8L5 21.5z" /><path className="l" d="M8.5 6h7M8.5 9.5h7" /><path className="l" d="M10 6c2.75 0 4.5 1 4.5 3.5S12.75 13 10 13l5.5 5" />
      </symbol>
      <symbol id="d-ceiling" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M6 17a6 6 0 0 1 12 0z" /><path className="l" d="M3.5 17a8.5 8.5 0 0 1 17 0M3.5 17h17" /><path className="l" d="M18 11l1.6-1.6" /><path className="l" d="M12 17l6.5-3.5" />
      </symbol>
      <symbol id="d-contract" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M6 17a6 6 0 0 1 12 0z" /><path className="l" d="M3.5 17a8.5 8.5 0 0 1 17 0M3.5 17h17" /><path className="l" d="M18 11l1.6-1.6" /><path className="l" d="M12 17l-3-7" />
      </symbol>
      <symbol id="d-site" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M4 19.5h8.5L10 9H6.5z" /><path className="l" d="M2.5 19.5h11.5M4 19.5L6.5 9h3.5l2.5 10.5" /><path className="l" d="M17.5 20.5c-2.8-3.2-4.2-5.6-4.2-8a4.2 4.2 0 0 1 8.4 0c0 2.4-1.4 4.8-4.2 8z" /><path className="l" d="M17.5 12.5h.01" />
      </symbol>
      <symbol id="d-tray" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M3 12h5l1.5 2.5h5L16 12h5v8H3z" /><path className="l" d="M3 12l2.5-7h13l2.5 7v8H3z" /><path className="l" d="M3 12h5l1.5 2.5h5L16 12h5" />
      </symbol>
      <symbol id="d-voucher" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M14.5 6.5h6v11h-6z" /><path className="l" d="M3.5 6.5h17v11h-17z" /><path className="l" strokeDasharray="2 2" d="M14.5 6.5v11" /><path className="l" d="M7 10.5h4M7 13.5h3" />
      </symbol>
      <symbol id="d-invoice-in" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M4 3h10v18H4z" /><path className="l" d="M4 3h10v18H4z" /><path className="l" d="M7 8h4M7 12h4M7 16h4" /><path className="l" d="M21.5 12H14M17 9l-3 3 3 3" />
      </symbol>
      <symbol id="d-invoice-out" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M4 3h10v18H4z" /><path className="l" d="M4 3h10v18H4z" /><path className="l" d="M7 8h4M7 12h4M7 16h4" /><path className="l" d="M14 12h7.5M18.5 9l3 3-3 3" />
      </symbol>
      <symbol id="d-orders" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M9 2.5h6v3.5H9z" /><path className="l" d="M5 5h14v16.5H5z" /><path className="l" d="M9 2.5h6v3.5H9z" /><path className="l" d="M8.5 11h7M8.5 14.5h7M8.5 18h4" />
      </symbol>
      <symbol id="d-due" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M12 12V4.5a7.5 7.5 0 0 1 7.5 7.5z" /><path className="l" d="M12 4.5a7.5 7.5 0 1 0 0 15a7.5 7.5 0 1 0 0-15z" /><path className="l" d="M12 7.5V12l3.5 2" />
      </symbol>
      <symbol id="d-stock" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M3.5 9.5h11v11h-11z" /><path className="l" d="M3.5 9.5h11v11h-11zM14.5 9.5l5-4v11l-5 4M3.5 9.5l5-4h11" /><path className="l" d="M9 9.5v11" />
      </symbol>
      <symbol id="d-count" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 3h14v5H5z" /><path className="l" d="M5 3h14v18H5z" /><path className="l" d="M8 12h8M8 16h5" />
      </symbol>
      <symbol id="d-people" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M16 5.5a3 3 0 1 1 0 6a3 3 0 1 1 0-6zM11 20v-1.5c0-3 2.5-5 5.5-5s5.5 2 5.5 5V20z" /><path className="l" d="M9 5.5a3.25 3.25 0 1 0 0 6.5a3.25 3.25 0 1 0 0-6.5z" /><path className="l" d="M2.5 20v-1.5c0-3 3-4.5 6.5-4.5s6.5 1.5 6.5 4.5V20z" />
      </symbol>
      <symbol id="d-held" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 11h14v10H5z" /><path className="l" d="M5 11h14v10H5z" /><path className="l" d="M8 11V8a4 4 0 0 1 8 0v3" /><path className="l" d="M12 15v2.5" />
      </symbol>
      <symbol id="d-firm" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 21V6l7-3 7 3v15z" /><path className="l" d="M5 21V6l7-3 7 3v15H5z" /><path className="l" d="M9 10h2M13 10h2M9 14h2M13 14h2M10 21v-4h4v4" />
      </symbol>
      <symbol id="d-flow" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M2.5 8h7v8h-7z" /><path className="l" d="M2.5 8h7v8h-7zM14.5 8h7v8h-7z" /><path className="l" d="M9.5 12h4M11.5 10l2 2-2 2" />
      </symbol>
      <symbol id="d-record" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M5 3h4v18H5z" /><path className="l" d="M5 3h14v18H5z" /><path className="l" d="M9 3v18M12.5 8h3M12.5 11.5h3" />
      </symbol>
      <symbol id="d-yours" viewBox="0 0 24 24" className="duo-art">
        <path className="k" d="M6 9.5h5v5H6z" /><path className="l" d="M2.5 5.5h19v13h-19z" /><path className="l" d="M6 9.5h5v5H6zM13.5 10h5M13.5 14h3.5" />
      </symbol>
      <symbol id="illo-today" viewBox="0 0 160 160" className="illo-art">
        <path className="fb" d="M22 104A24 24 0 0 1 70 104Z" /><path className="fc" d="M14 104Q80 100 146 105L146 112Q80 108 14 112Z" /><path className="fa" d="M88 44L144 42L146 86L90 88Z" /><path className="fn" d="M96 52L138 51L139 64L97 65Z" /><path className="l" d="M22 104A24 24 0 0 1 70 104" /><path className="l" d="M46 66V74M29 73l5 6M63 73l-5 6M12 90l8 3M80 90l-8 3" /><path className="l" d="M14 104Q80 100 146 105" /><path className="l" d="M88 44L144 42L146 86L90 88ZM97 65Q118 64 139 64M98 88V102M136 86V104" /><path className="sp" d="M24 38Q24 44 30 44Q24 44 24 50Q24 44 18 44Q24 44 24 38Z" /><path className="sp" d="M148 19Q148 24 153 24Q148 24 148 29Q148 24 143 24Q148 24 148 19Z" /><path className="sp" d="M134 126Q134 130 138 130Q134 130 134 134Q134 130 130 130Q134 130 134 126Z" />
      </symbol>
      <symbol id="illo-tasks" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M40 34Q80 31 120 32L122 136Q81 139 42 138Z" /><path className="fa" d="M64 26L96 25L98 40L66 41Z" /><path className="fc" d="M50 56L64 55L65 69L51 70Z" /><path className="fc" d="M51 80L65 79L66 93L52 94Z" /><path className="l" d="M40 34Q80 31 120 32L122 136Q81 139 42 138Z" /><path className="l" d="M64 26L96 25L98 40L66 41ZM72 26Q72 18 80 18Q88 18 88 25" /><path className="l" d="M50 56L64 55L65 69L51 70ZM53 63l4 4 7-8" /><path className="l" d="M51 80L65 79L66 93L52 94ZM54 87l4 4 7-8" /><path className="l" d="M52 104L66 103L67 117L53 118ZM53 122L67 121" /><path className="l" d="M74 62h34M74 86h28M75 110h32" /><path className="sp" d="M24 42Q24 48 30 48Q24 48 24 54Q24 48 18 48Q24 48 24 42Z" /><path className="sp" d="M138 47Q138 52 143 52Q138 52 138 57Q138 52 133 52Q138 52 138 47Z" /><path className="sp" d="M140 114Q140 118 144 118Q140 118 140 122Q140 118 136 118Q140 118 140 114Z" />
      </symbol>
      <symbol id="illo-notifications" viewBox="0 0 160 160" className="illo-art">
        <path className="fb" d="M42 108Q51 101 50 90Q54 46 80 40Q106 46 110 90Q109 101 118 108Z" /><path className="fn" d="M38 108Q80 104 122 108L124 120Q80 124 36 120Z" /><path className="l" d="M42 108Q51 101 50 90Q54 46 80 40Q106 46 110 90Q109 101 118 108" /><path className="l" d="M77 40Q80 31 83 40" /><path className="l" d="M38 108Q80 104 122 108L124 120Q80 124 36 120Z" /><path className="l" d="M80 120V126M76 130a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" /><path className="l" d="M126 60l6 6 10-12" /><path className="sp" d="M24 34Q24 40 30 40Q24 40 24 46Q24 40 18 40Q24 40 24 34Z" /><path className="sp" d="M140 91Q140 96 145 96Q140 96 140 101Q140 96 135 96Q140 96 140 91Z" /><path className="sp" d="M28 128Q28 132 32 132Q28 132 28 136Q28 132 24 132Q28 132 28 128Z" />
      </symbol>
      <symbol id="illo-sales" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M30 42Q80 39 130 40L131 122Q80 125 32 122Z" /><path className="fa" d="M44 62Q44 48 58 48Q72 48 72 62Q72 76 58 76Q44 76 44 62Z" /><path className="fc" d="M92 100L128 99L129 116L93 117Z" /><path className="fb" d="M38 92Q58 82 78 92L78 110L38 110Z" /><path className="l" d="M30 42Q80 39 130 40L131 122Q80 125 32 122Z" /><path className="l" d="M44 62Q44 48 58 48Q72 48 72 62Q72 76 58 76Q44 76 44 62ZM38 92Q58 82 78 92" /><path className="l" d="M84 56h34M84 70h24" /><path className="l" d="M92 100L128 99L129 116L93 117ZM100 108h20" /><path className="sp" d="M20 24Q20 30 26 30Q20 30 20 36Q20 30 14 30Q20 30 20 24Z" /><path className="sp" d="M142 47Q142 52 147 52Q142 52 142 57Q142 52 137 52Q142 52 142 47Z" /><path className="sp" d="M140 132Q140 136 144 136Q140 136 140 140Q140 136 136 136Q140 136 140 132Z" />
      </symbol>
      <symbol id="illo-projects" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M34 36L126 34L128 126L36 128Z" /><path className="fc" d="M36 38L82 37L83 78L37 79Z" /><path className="fb" d="M84 82L126 81L127 125L85 126Z" /><path className="l" d="M34 36L126 34L128 126L36 128Z" /><path className="l" d="M82 37L83 126M37 79L127 80" /><path className="l" d="M83 60V78M83 60Q98 60 100 78" /><path className="l" d="M100 34V50M110 34V50" /><path className="sp" d="M20 20Q20 26 26 26Q20 26 20 32Q20 26 14 26Q20 26 20 20Z" /><path className="sp" d="M142 57Q142 62 147 62Q142 62 142 67Q142 62 137 62Q142 62 142 57Z" /><path className="sp" d="M146 134Q146 138 150 138Q146 138 146 142Q146 138 142 138Q146 138 146 134Z" />
      </symbol>
      <symbol id="illo-boq" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M38 22Q78 19 118 18L124 136Q83 139 42 140Z" /><path className="fa" d="M39 23Q78 20 118 19L119 40Q80 41 40 44Z" /><path className="fb" d="M41 80Q81 78 121 77L122 96Q82 98 42 99Z" /><path className="l" d="M38 22Q78 19 118 18L124 136Q83 139 42 140Z" /><path className="l" d="M40 44Q80 41 119 40" /><path className="l" d="M96 41L100 137" /><path className="l" d="M41 62Q81 60 120 59M41 80Q81 78 121 77M42 99Q82 97 122 96M42 118Q83 116 123 115" /><path className="l" d="M50 32h26M104 30h8" /><path className="l" d="M50 53h30M106 51h7M50 71h22M106 69h9M51 89h34M107 88h8M51 108h26M107 106h9" /><g transform="rotate(-42 124 126)"><path className="fb" d="M100 120h44v12h-44z" /><path className="a" d="M144 120h9v12h-9z" /><path className="l" d="M100 120h53v12h-53zM144 120v12M100 120l-13 6 13 6" /></g><path className="sp" d="M24 30Q24 36 30 36Q24 36 24 42Q24 36 18 36Q24 36 24 30Z" /><path className="sp" d="M140 39Q140 44 145 44Q140 44 140 49Q140 44 135 44Q140 44 140 39Z" /><path className="sp" d="M22 108Q22 112 26 112Q22 112 22 116Q22 112 18 112Q22 112 22 108Z" />
      </symbol>
      <symbol id="illo-rates" viewBox="0 0 160 160" className="illo-art">
        <path className="fa" d="M44 28Q80 25 116 26L118 134Q80 137 42 134Z" /><path className="fn" d="M54 38L106 37L107 60L55 61Z" /><path className="fb" d="M84 104L106 103L107 124L85 125Z" /><path className="l" d="M44 28Q80 25 116 26L118 134Q80 137 42 134Z" /><path className="l" d="M54 38L106 37L107 60L55 61ZM72 50h26" /><path className="l" d="M54 72h12M70 72h12M86 72h12M54 88h12M70 88h12M86 88h12M54 104h12M70 104h12M54 120h28" /><path className="l" d="M84 104L106 103L107 124L85 125ZM90 111h10M90 117h10" /><path className="sp" d="M22 38Q22 44 28 44Q22 44 22 50Q22 44 16 44Q22 44 22 38Z" /><path className="sp" d="M138 31Q138 36 143 36Q138 36 138 41Q138 36 133 36Q138 36 138 31Z" /><path className="sp" d="M140 112Q140 116 144 116Q140 116 140 120Q140 116 136 116Q140 116 140 112Z" />
      </symbol>
      <symbol id="illo-orders" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M32 30Q80 27 128 28L130 130Q80 133 34 130Z" /><path className="fa" d="M33 31Q80 28 128 29L128 50Q80 51 34 53Z" /><path className="fb" d="M96 100L124 99L125 118L97 119Z" /><path className="fc" d="M38 62L74 61L75 70L39 71Z" /><path className="l" d="M32 30Q80 27 128 28L130 130Q80 133 34 130Z" /><path className="l" d="M34 53Q80 51 128 50" /><path className="l" d="M38 62L74 61L75 70L39 71ZM86 66h34M40 84h44M104 84h16M41 96h30M104 96h16" /><path className="l" d="M96 100L124 99L125 118L97 119ZM102 109h16" /><path className="l" d="M42 40h30" /><path className="sp" d="M20 38Q20 44 26 44Q20 44 20 50Q20 44 14 44Q20 44 20 38Z" /><path className="sp" d="M142 35Q142 40 147 40Q142 40 142 45Q142 40 137 40Q142 40 142 35Z" /><path className="sp" d="M146 126Q146 130 150 130Q146 130 146 134Q146 130 142 130Q146 130 146 126Z" />
      </symbol>
      <symbol id="illo-stock" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M34 70L62 50L130 50L102 72Z" /><path className="fb" d="M34 70L102 72L100 134L36 132Z" /><path className="fa" d="M102 72L130 50L128 112L100 134Z" /><path className="a" d="M54 97L80 96L81 113L55 114Z" /><path className="l" d="M34 70L102 72L100 134L36 132ZM34 70L62 50Q96 49 130 50L102 72M130 50L128 112L100 134" /><path className="l" d="M45 71L46 133M91 72L90 134" /><path className="l" d="M54 97L80 96L81 113L55 114ZM59 103h15M59 108h10" /><path className="l" d="M115 102V78M109 85L115 78L121 83" /><path className="sp" d="M22 36Q22 42 28 42Q22 42 22 48Q22 42 16 42Q22 42 22 36Z" /><path className="sp" d="M142 25Q142 30 147 30Q142 30 142 35Q142 30 137 30Q142 30 142 25Z" /><path className="sp" d="M146 118Q146 122 150 122Q146 122 146 126Q146 122 142 122Q146 122 146 118Z" />
      </symbol>
      <symbol id="illo-vendors" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M36 46L124 44L126 132L38 134Z" /><path className="fb" d="M28 50L132 48L126 68L34 68Z" /><path className="fn" d="M42 49.7L54 49.5L55 68L43 68ZM66 49.3L78 49L79 68L67 68ZM90 48.8L102 48.6L103 68L91 68ZM114 48.3L126 48.1L124 68L115 68Z" /><path className="fa" d="M40 30L120 28L122 44L38 46Z" /><path className="fa" d="M52 96L74 95L75 133L53 134Z" /><path className="fc" d="M88 90L116 89L117 110L89 111Z" /><path className="fn" d="M85 111L120 110L120 115L85 116Z" /><path className="l" d="M36 46L38 134L126 132L124 44" /><path className="l" d="M28 50L132 48L126 68L34 68Z" /><path className="l" d="M34 68Q39.75 76 45.5 68Q51.25 76 57 68Q62.75 76 68.5 68Q74.25 76 80 68Q85.75 76 91.5 68Q97.25 76 103 68Q108.75 76 114.5 68Q120.25 76 126 68" /><path className="l" d="M40 30L120 28L122 44L38 46ZM56 37h48" /><path className="l" d="M52 96L74 95L75 133L53 134ZM67 117a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path className="l" d="M88 90L116 89L117 110L89 111ZM102 89.5V110.5M88.5 100.5L116.5 99.5M85 111L120 110L120 115L85 116Z" /><path className="l" d="M18 140Q80 136 142 140" /><path className="sp" d="M20 18Q20 24 26 24Q20 24 20 30Q20 24 14 24Q20 24 20 18Z" /><path className="sp" d="M146 25Q146 30 151 30Q146 30 146 35Q146 30 141 30Q146 30 146 25Z" /><path className="sp" d="M146 124Q146 128 150 128Q146 128 146 132Q146 128 142 128Q146 128 146 124Z" />
      </symbol>
      <symbol id="illo-approvals" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M44 62L116 60L128 84L32 86Z" /><path className="fa" d="M30 86L130 84L128 120L32 122Z" /><path className="l" d="M44 62L116 60L128 84L32 86ZM30 86L130 84L128 120L32 122Z" /><path className="l" d="M72 102h16" /><path className="l" d="M70 74l7 7 13-14" /><path className="sp" d="M24 34Q24 40 30 40Q24 40 24 46Q24 40 18 40Q24 40 24 34Z" /><path className="sp" d="M138 39Q138 44 143 44Q138 44 138 49Q138 44 133 44Q138 44 138 39Z" /><path className="sp" d="M140 126Q140 130 144 130Q140 130 140 134Q140 130 136 130Q140 130 140 126Z" />
      </symbol>
      <symbol id="illo-daily" viewBox="0 0 160 160" className="illo-art">
        <path className="fa" d="M36 72Q30 30 76 26Q124 22 126 66Q130 106 86 110Q42 114 36 72Z" /><path className="fc" d="M26 134Q80 126 136 133Q82 142 26 134Z" /><path className="fb" d="M76 28Q80 22 84 28L108 118L52 120Z" /><path className="fn" d="M68.7 56L91.5 56L95.2 70L65 70ZM60.3 88L100 88L103.7 102L56.7 102Z" /><path className="fb" d="M38 120Q80 117 122 118L126 132Q80 135 34 134Z" /><path className="l" d="M76 28Q80 22 84 28L108 118M52 120L76 28" /><path className="l" d="M68.7 56Q80 55 91.5 56M65 70Q80 71 95.2 70M60.3 88Q80 87 100 88M56.7 102Q80 103 103.7 102" /><path className="l" d="M38 120Q80 117 122 118L126 132Q80 135 34 134Z" /><path className="sp" d="M26 24Q26 30 32 30Q26 30 26 36Q26 30 20 30Q26 30 26 24Z" /><path className="sp" d="M138 31Q138 36 143 36Q138 36 138 41Q138 36 133 36Q138 36 138 31Z" /><path className="sp" d="M144 92Q144 96 148 96Q144 96 144 100Q144 96 140 96Q144 96 144 92Z" />
      </symbol>
      <symbol id="illo-measure" viewBox="0 0 160 160" className="illo-art">
        <path className="fb" d="M94 104L146 102L147 115L94 117Z" /><path className="fa" d="M28 60Q28 48 40 48L86 47Q98 47 98 60L99 106Q99 118 86 118L40 119Q28 119 28 106Z" /><path className="fn" d="M52 83Q52 72 63 72Q74 72 74 83Q74 94 63 94Q52 94 52 83Z" /><path className="a" d="M50 48L51 40L70 39L71 47Z" /><path className="l" d="M28 60Q28 48 40 48L86 47Q98 47 98 60L99 106Q99 118 86 118L40 119Q28 119 28 106Z" /><path className="l" d="M52 83Q52 72 63 72Q74 72 74 83Q74 94 63 94Q52 94 52 83ZM62 83h2" /><path className="l" d="M50 48L51 40L70 39L71 47" /><path className="l" d="M99 104L146 102L147 115L99 117" /><path className="l" d="M108 103.5v5M117 103v8M126 103v5M135 102.5v8M144 102v5" /><path className="l" d="M146 100L152 99.5L153 118L147 118" /><path className="l" d="M24 66L24 100" /><path className="sp" d="M22 24Q22 30 28 30Q22 30 22 36Q22 30 16 30Q22 30 22 24Z" /><path className="sp" d="M120 39Q120 44 125 44Q120 44 120 49Q120 44 115 44Q120 44 120 39Z" /><path className="sp" d="M138 74Q138 78 142 78Q138 78 138 82Q138 78 134 78Q138 78 138 74Z" />
      </symbol>
      <symbol id="illo-recce" viewBox="0 0 160 160" className="illo-art">
        <path className="fa" d="M32 62L128 60L130 120L34 122Z" /><path className="fn" d="M56 91a24 24 0 1 0 48 0a24 24 0 1 0 -48 0Z" /><path className="fc" d="M67 91a13 13 0 1 0 26 0a13 13 0 1 0 -26 0Z" /><path className="fb" d="M106 68L122 67L123 76L107 77Z" /><path className="l" d="M32 62L128 60L130 120L34 122Z" /><path className="l" d="M64 62L68 50L92 49L96 61" /><path className="l" d="M56 91a24 24 0 1 0 48 0a24 24 0 1 0 -48 0M67 91a13 13 0 1 0 26 0a13 13 0 1 0 -26 0" /><path className="l" d="M106 68L122 67L123 76L107 77Z" /><path className="l" d="M36 62Q42 28 80 26Q118 28 124 60" /><path className="sp" d="M18 38Q18 44 24 44Q18 44 18 50Q18 44 12 44Q18 44 18 38Z" /><path className="sp" d="M142 35Q142 40 147 40Q142 40 142 45Q142 40 137 40Q142 40 142 35Z" /><path className="sp" d="M146 122Q146 126 150 126Q146 126 146 130Q146 126 142 126Q146 126 146 122Z" />
      </symbol>
      <symbol id="illo-documents" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M38 56L36 132Q80 135 124 130L122 54Z" /><path className="fc" d="M49 70L80 69L81 95L49 96Z" /><path className="fb" d="M81 100L112 99L113 118L81 119Z" /><path className="fa" d="M34 34Q80 31 128 32L128 54Q80 53 34 56Z" /><path className="l" d="M38 56L36 132Q80 135 124 130L122 54" /><path className="l" d="M34 34Q80 31 128 32M128 54Q80 53 34 56" /><path className="l" d="M34 34Q27 34 28 45Q28 56 34 56M128 32Q134 32 134 43Q134 54 128 54Q122 54 122 43Q122 32 128 32Z" /><path className="l" d="M128 38Q125 38 125 43Q125 48 128 48" /><path className="l" d="M48 70L112 68L113 118L49 120ZM80 69L81 100M49 96L68 95M81 100L112 99" /><path className="l" d="M68 95Q70 103 80 104" /><path className="sp" d="M20 20Q20 26 26 26Q20 26 20 32Q20 26 14 26Q20 26 20 20Z" /><path className="sp" d="M146 67Q146 72 151 72Q146 72 146 77Q146 72 141 72Q146 72 146 67Z" /><path className="sp" d="M20 100Q20 104 24 104Q20 104 20 108Q20 104 16 104Q20 104 20 100Z" />
      </symbol>
      <symbol id="illo-money" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M28 34Q72 31 116 30L120 124L112 130L104 124L96 130L88 124L80 130L72 124L64 130L56 124L48 130L40 124L32 130Z" /><path className="fa" d="M29 35Q72 32 116 31L117 50Q73 51 30 53Z" /><path className="fb" d="M84 58L110 57L111 70L85 71Z" /><path className="a" fillRule="evenodd" d="M68 100a22 22 0 1 0 44 0a22 22 0 1 0 -44 0ZM74 100a16 16 0 1 0 32 0a16 16 0 1 0 -32 0Z" /><path className="l" d="M28 34Q72 31 116 30L120 124L112 130L104 124L96 130L88 124L80 130L72 124L64 130L56 124L48 130L40 124L32 130Z" /><path className="l" d="M30 53Q73 51 117 50" /><path className="l" d="M38 42h24M38 64h40M38 76h30M38 88h20M38 108h14" /><path className="l" d="M68 100a22 22 0 1 0 44 0a22 22 0 1 0 -44 0" /><path className="l" d="M79 100l7 7 15-16" /><path className="l" d="M84 58L110 57L111 70L85 71ZM90 64h14" /><path className="sp" d="M18 25Q18 30 23 30Q18 30 18 35Q18 30 13 30Q18 30 18 25Z" /><path className="sp" d="M150 94Q150 100 156 100Q150 100 150 106Q150 100 144 100Q150 100 150 94Z" /><path className="sp" d="M138 134Q138 138 142 138Q138 138 138 142Q138 138 134 138Q138 138 138 134Z" />
      </symbol>
      <symbol id="illo-chai" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M30 112Q80 108 130 112L126 124Q80 130 34 124Z" /><path className="fa" d="M50 64L56 110Q80 118 104 110L110 64Q80 70 50 64Z" /><path className="fb" d="M50 64Q80 58 110 64Q80 70 50 64Z" /><path className="l" d="M56 110Q42 110 30 112L34 124Q80 130 126 124L130 112Q118 110 104 110" /><path className="l" d="M50 64L56 110Q80 118 104 110L110 64" /><path className="l" d="M50 64Q80 58 110 64Q80 70 50 64Z" /><path className="l" d="M110 76Q132 76 130 92Q128 102 106 102" /><path className="l" d="M70 48Q65 40 70 32Q75 24 70 16M90 46Q85 38 90 30Q95 22 90 14" /><path className="sp" d="M24 30Q24 36 30 36Q24 36 24 42Q24 36 18 36Q24 36 24 30Z" /><path className="sp" d="M140 25Q140 30 145 30Q140 30 140 35Q140 30 135 30Q140 30 140 25Z" /><path className="sp" d="M146 116Q146 120 150 120Q146 120 146 124Q146 120 142 120Q146 120 146 116Z" />
      </symbol>
      <symbol id="illo-search" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M44 68a28 28 0 1 0 56 0a28 28 0 1 0 -56 0Z" /><path className="l" d="M44 68a28 28 0 1 0 56 0a28 28 0 1 0 -56 0" /><path className="l" d="M92 88L124 120Q128 124 124 128Q120 132 116 128L84 96" /><path className="l" d="M56 60Q60 52 70 50" /><path className="sp" d="M24 30Q24 36 30 36Q24 36 24 42Q24 36 18 36Q24 36 24 30Z" /><path className="sp" d="M136 39Q136 44 141 44Q136 44 136 49Q136 44 131 44Q136 44 136 39Z" /><path className="sp" d="M30 118Q30 122 34 122Q30 122 30 126Q30 122 26 122Q30 122 30 118Z" />
      </symbol>
      <symbol id="illo-not-found" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M46 52L104 50L114 60L104 70L46 72Z" /><path className="fn" d="M116 84L58 82L48 92L58 102L116 104Z" /><path className="l" d="M46 52L104 50L114 60L104 70L46 72ZM116 84L58 82L48 92L58 102L116 104Z" /><path className="l" d="M80 34V52M80 72V82M80 104V134M66 134h28" /><path className="l" d="M56 61h30M70 93h30" /><path className="sp" d="M24 34Q24 40 30 40Q24 40 24 46Q24 40 18 40Q24 40 24 34Z" /><path className="sp" d="M138 31Q138 36 143 36Q138 36 138 41Q138 36 133 36Q138 36 138 31Z" /><path className="sp" d="M140 120Q140 124 144 124Q140 124 140 128Q140 124 136 124Q140 124 140 120Z" />
      </symbol>
      <symbol id="illo-unreachable" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M30 74L62 72L64 96L32 98Z" /><path className="fn" d="M100 66L132 64L134 104L102 106Z" /><path className="l" d="M30 74L62 72L64 96L32 98ZM64 78h10M64 90h10" /><path className="l" d="M100 66L132 64L134 104L102 106ZM110 78v10M124 77v10" /><path className="l" d="M30 86Q14 86 14 104Q14 122 40 122Q70 122 80 130" /><path className="l" d="M134 84h14" /><path className="sp" d="M22 34Q22 40 28 40Q22 40 22 46Q22 40 16 40Q22 40 22 34Z" /><path className="sp" d="M138 31Q138 36 143 36Q138 36 138 41Q138 36 133 36Q138 36 138 31Z" /><path className="sp" d="M112 128Q112 132 116 132Q112 132 112 136Q112 132 108 132Q112 132 112 128Z" />
      </symbol>
      <symbol id="illo-error" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M80 34L136 128L24 130Z" /><path className="l" d="M80 34L136 128L24 130Z" /><path className="l" d="M80 64V96M80 108V112" /><path className="sp" d="M22 38Q22 44 28 44Q22 44 22 50Q22 44 16 44Q22 44 22 38Z" /><path className="sp" d="M140 39Q140 44 145 44Q140 44 140 49Q140 44 135 44Q140 44 140 39Z" /><path className="sp" d="M146 128Q146 132 150 132Q146 132 146 136Q146 132 142 132Q146 132 146 128Z" />
      </symbol>
      <symbol id="illo-signed-out" viewBox="0 0 160 160" className="illo-art">
        <path className="fn" d="M36 74a22 22 0 1 0 44 0a22 22 0 1 0 -44 0Z" /><path className="l" d="M36 74a22 22 0 1 0 44 0a22 22 0 1 0 -44 0M52 74a6 6 0 1 0 12 0a6 6 0 1 0 -12 0" /><path className="l" d="M80 74L136 72M112 72V86M126 72V82" /><path className="sp" d="M24 34Q24 40 30 40Q24 40 24 46Q24 40 18 40Q24 40 24 34Z" /><path className="sp" d="M140 39Q140 44 145 44Q140 44 140 49Q140 44 135 44Q140 44 140 39Z" /><path className="sp" d="M140 114Q140 118 144 118Q140 118 140 122Q140 118 136 118Q140 118 140 114Z" />
      </symbol>
      <symbol id="illo-operator" viewBox="0 0 160 160" className="illo-art">
        <path className="fa" d="M28 68L58 66L60 130L30 131Z" /><path className="fc" d="M64 44L100 42L102 130L66 131Z" /><path className="fb" d="M106 78L134 76L136 130L108 131Z" /><path className="l" d="M28 68L58 66L60 130L30 131ZM64 44L100 42L102 130L66 131ZM106 78L134 76L136 130L108 131Z" /><path className="l" d="M36 78h6M48 78h6M36 92h6M48 92h6M36 106h6M48 106h6M72 54h8M86 54h8M72 68h8M86 68h8M72 82h8M86 82h8M72 96h8M86 96h8M114 88h6M126 88h6M114 102h6M126 102h6" /><path className="l" d="M18 132Q80 129 142 132" /><path className="sp" d="M20 28Q20 34 26 34Q20 34 20 40Q20 34 14 34Q20 34 20 28Z" /><path className="sp" d="M140 35Q140 40 145 40Q140 40 140 45Q140 40 135 40Q140 40 140 35Z" /><path className="sp" d="M146 96Q146 100 150 100Q146 100 146 104Q146 100 142 100Q146 100 146 96Z" />
      </symbol>
    </>
  );
}
